services:
  web:
    environment:
    command: npm run dev -- --host

  webrtc:

  nginx:
    build:
      context: ../nginx
      dockerfile: Dockerfile.ssl
    environment:
      - ENV=dev
      - WEB_UPSTREAM=tafu-web:9000
      - WEBRTC_UPSTREAM=tafu-webrtc:9000
    ports:
      - "443:443"  # HTTPS
    volumes:
      - ./setup/certs:/etc/nginx/certs:ro
      - ../nginx/scripts:/usr/local/bin