services:
  web:
    build: 
      context: ../../
      target: development
    container_name: tafu-web
    ports:
      - "9000:9000"
    volumes:
      - ../../:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: npm run dev -- --host
    stop_signal: SIGINT
    stop_grace_period: 1s

  webrtc:
    build:
      context: ../../
      dockerfile: server/Dockerfile
    container_name: tafu-webrtc
    ports:
      - "9001:9000"      # WebSocket
      - "2000-2020:2000-2020/udp"  # WebRTC media
    volumes:
      - ../../server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    stop_signal: SIGINT
    stop_grace_period: 1s

  nginx:
    build: 
      context: ../nginx
      dockerfile: Dockerfile.dev
    ports:
      - "1935:1935"
      - "8080:8080"
    volumes:
      - ./setup/certs:/etc/nginx/certs
      - ../nginx/scripts:/usr/local/bin
    environment:
      - WEB_UPSTREAM=tafu-web:9000
      - WEBRTC_UPSTREAM=tafu-webrtc:9000
    stop_signal: SIGTERM
    stop_grace_period: 1s