services:
  web:
    build: 
      context: ../../
      target: development
    container_name: tafu-web
    ports:
      - "3000:3000"
    volumes:
      - ../../:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host
    stop_signal: SIGINT
    stop_grace_period: 1s

  webrtc:
    build: ../../server
    container_name: tafu-webrtc
    ports:
      - "3001:3001"      # WebSocket
      - "2000-2020:2000-2020/udp"  # WebRTC media
    volumes:
      - ../../server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    stop_signal: SIGINT
    stop_grace_period: 1s

  nginx:
    build: 
      context: ../nginx
      dockerfile: Dockerfile.dev
    ports:
      - "1935:1935"
      - "8080:8080"
    volumes:
      - ./setup/certs:/etc/nginx/certs
    stop_signal: SIGTERM
    stop_grace_period: 1s