services:
  web:
    ports:
      - "3443:3443"  # HTTPS port
    volumes:
      - ./setup/certs:/app/certs    # Additional SSL certs, doesn't affect hot reload
    environment:
      - USE_SSL=true
      - VITE_USE_SSL=true
    command: npm run dev -- --host --port 3443

  webrtc:
    volumes:
      - ./setup/certs:/app/certs:ro
    environment:
      - USE_SSL=true

  nginx:
    build:
      context: ../nginx
      dockerfile: Dockerfile.ssl
    ports:
      - "8443:8080"  # Map to 8443 for SSL
    volumes:
      - ./setup/certs:/etc/nginx/certs:ro 