services:
  webrtc:
    build: ./server
    container_name: tafu-webrtc
    ports:
      - "3001:3001"
      - "2000-2020:2000-2020/udp"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    stop_signal: SIGINT
    stop_grace_period: 1s

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "1935:1935"
      - "8080:8080"
    stop_signal: SIGTERM
    stop_grace_period: 1s 