version: '3.8'

services:
  web:
    build: .
    container_name: tafu-web
    ports:
      - "3000:3000"
      - "24678:24678" # Vite HMR port
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host

  webrtc:
    build: ./server
    container_name: tafu-webrtc
    ports:
      - "3001:3001"      # WebSocket
      - "2000-2020:2000-2020/udp"  # WebRTC media
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev