services:
  web:
    image: tafu-web:pr-${PR_NUMBER}
    container_name: pr-${PR_NUMBER}-web
    environment:
      - NODE_ENV=production
      - PR_PREVIEW=true
      - PR_NUMBER=${PR_NUMBER}
      - VIRTUAL_HOST=pr-${PR_NUMBER}.demo.tafu.casa
      - VIRTUAL_PORT=9000
    ports:
      - "9000"
    networks:
      - nginx-proxy

  webrtc:
    image: tafu-webrtc:pr-${PR_NUMBER}
    container_name: pr-${PR_NUMBER}-webrtc
    environment:
      - NODE_ENV=production
      - PR_PREVIEW=true
      - VIRTUAL_HOST=webrtc-pr-${PR_NUMBER}.demo.tafu.casa
      - VIRTUAL_PORT=9000
    expose:
      - "9000"
    networks:
      - nginx-proxy

  nginx:
    image: tafu-nginx:pr-${PR_NUMBER}
    container_name: pr-${PR_NUMBER}-nginx
    environment:
      - VIRTUAL_HOST=stream-pr-${PR_NUMBER}.demo.tafu.casa
      - VIRTUAL_PORT=8080
      - WEB_UPSTREAM=pr-${PR_NUMBER}-web
      - WEBRTC_UPSTREAM=pr-${PR_NUMBER}-webrtc
    expose:
      - "8080"
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true 