version: '3'
services:
  web:
    image: tafu-web:${TAG:-latest}
    restart: unless-stopped
    ports:
      - "${PORT:-3443}:3000"
    environment:
      - NODE_ENV=production
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true 