services:
  web:
    image: tafu-web:${TAG}
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PORT=3000
    expose:
      - "3000"
    networks:
      - nginx-proxy

  webrtc:
    image: tafu-webrtc:${TAG}
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=webrtc.${DOMAIN}
      - VIRTUAL_PORT=3001
    expose:
      - "3001"
    networks:
      - nginx-proxy

  nginx:
    image: tafu-nginx:${TAG}
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=stream.${DOMAIN}
      - VIRTUAL_PORT=9000
      - WEB_UPSTREAM=${TAG}-web-1
      - WEBRTC_UPSTREAM=${TAG}-webrtc-1
    expose:
      - "9000"
    networks:
      - nginx-proxy

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-master
    ports:
      - "8080:80"    # Map container's 80 to host's 8080
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true 