services:
  web:
    image: tafu-web:${TAG}
    restart: unless-stopped
    ports:
      - "${PORT:-3443}:3000"
    environment:
      - NODE_ENV=production
    networks:
      - nginx-proxy

  webrtc:
    image: tafu-webrtc:${TAG}
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - nginx-proxy

  nginx:
    image: tafu-nginx:${TAG}
    restart: unless-stopped
    environment:
      - WEB_UPSTREAM=prod-web-1
      - WEBRTC_UPSTREAM=prod-webrtc-1
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true 