FROM alpine:3.18

RUN apk update && apk add --no-cache \
    nginx \
    nginx-mod-rtmp \
    ffmpeg \
    findutils

RUN mkdir -p /var/www/hls && \
    mkdir -p /var/www/dash && \
    chown -R nginx:nginx /var/www

COPY nginx.dev.conf /etc/nginx/nginx.conf
COPY cleanup.sh /usr/local/bin/cleanup.sh
RUN chmod +x /usr/local/bin/cleanup.sh

EXPOSE 1935
EXPOSE 8080

CMD sh -c "/usr/local/bin/cleanup.sh & nginx -g 'daemon off;'" 