name: Deploy Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: [self-hosted, external]
    steps:
      - name: Checkout code
        run: |
          rm -rf * .[^.]*
          git init
          git remote add origin https://github.com/${{ github.repository }}
          git fetch origin ${{ github.sha }}
          git checkout ${{ github.sha }}

      - uses: ./.github/actions/checkout

      - name: Set up environment variables
        run: |
          echo "DEPLOY_ENV=prod" >> $GITHUB_ENV
          echo "DOMAIN=tafu.casa" >> $GITHUB_ENV

      - name: Build images
        run: |
          docker build \
            --build-arg DOMAIN=$DOMAIN \
            -t tafu-web:prod \
            -f Dockerfile .
          docker build \
            --build-arg DOMAIN=$DOMAIN \
            -t tafu-webrtc:prod \
            -f server/Dockerfile .
          docker build \
            --build-arg DOMAIN=$DOMAIN \
            -t tafu-nginx:prod \
            -f docker/nginx/Dockerfile.ssl \
            docker/nginx

      - name: Deploy
        run: |
          docker network create nginx-proxy || true
          TAG=prod docker compose -f docker/prod/docker-compose.yml down
          TAG=prod docker compose -f docker/prod/docker-compose.yml up -d

      - name: Clean up old images
        run: docker image prune -f 