name: Deploy Staging

on:
  push:
    branches: [staging]

jobs:
  deploy:
    runs-on: [self-hosted, internal]
    steps:
      - name: Checkout code
        run: |
          rm -rf * .[^.]*
          git init
          git remote add origin https://github.com/${{ github.repository }}
          git fetch origin ${{ github.sha }}
          git checkout ${{ github.sha }}

      - uses: ./.github/actions/checkout

      - name: Set up environment variables
        run: |
          echo "DEPLOY_ENV=staging" >> $GITHUB_ENV
          echo "DOMAIN=staging.tafu.casa" >> $GITHUB_ENV

      - name: Build images
        run: |
          docker build \
            --build-arg DOMAIN=$DOMAIN \
            -t tafu-web:staging \
            -f Dockerfile .
          docker build \
            --build-arg DOMAIN=$DOMAIN \
            -t tafu-webrtc:staging \
            -f server/Dockerfile .
          docker build \
            --build-arg DOMAIN=$DOMAIN \
            -t tafu-nginx:staging \
            -f docker/nginx/Dockerfile.ssl \
            docker/nginx

      - name: Deploy
        run: |
          # Ensure nginx-proxy is running and healthy
          docker network create nginx-proxy || true
          if ! docker ps -q -f name=nginx-master; then
            docker compose -f docker/prod/docker-compose.yml up -d nginx-proxy
            sleep 5  # Give it time to start up
          fi
          
          # Stop and remove only staging containers
          docker stop staging-web staging-webrtc staging-nginx || true
          docker rm staging-web staging-webrtc staging-nginx || true
          
          # Deploy new containers
          TAG=staging docker compose -f docker/prod/docker-compose.yml -f docker/prod/docker-compose.staging.yml up -d
          
          # Wait for containers to be healthy
          echo "Waiting for containers to be ready..."
          sleep 10

      - name: Clean up old images
        run: docker image prune -f 