name: Deploy Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: [self-hosted, external]
    steps:
      - name: Checkout code
        run: |
          rm -rf * .[^.]*
          git init
          git remote add origin https://github.com/${{ github.repository }}
          git fetch origin ${{ github.sha }}
          git checkout ${{ github.sha }}

      - uses: ./.github/actions/checkout

      - name: Set up environment variables
        run: |
          echo "DEPLOY_ENV=prod" >> $GITHUB_ENV
          echo "DOMAIN=tafu.casa" >> $GITHUB_ENV

      - name: Build images
        run: |
          docker build \
            --build-arg DOMAIN=$DOMAIN \
            -t tafu-web:prod \
            -f Dockerfile .
          docker build \
            --build-arg DOMAIN=$DOMAIN \
            -t tafu-webrtc:prod \
            -f server/Dockerfile .
          docker build \
            --build-arg DOMAIN=$DOMAIN \
            -t tafu-nginx:prod \
            -f docker/nginx/Dockerfile.ssl \
            docker/nginx

      - name: Deploy
        run: |
          # Ensure nginx-proxy is running and healthy
          docker network create nginx-proxy || true
          if ! docker ps -q -f name=nginx-master; then
            docker compose -f docker/prod/docker-compose.yml up -d nginx-proxy
            sleep 5  # Give it time to start up
          fi
          
          # Stop and remove only production containers
          docker stop prod-web-1 prod-webrtc-1 prod-nginx-1 || true
          docker rm prod-web-1 prod-webrtc-1 prod-nginx-1 || true
          
          # Deploy new containers
          TAG=prod docker compose -f docker/prod/docker-compose.yml up -d
          
          # Wait for containers to be healthy
          echo "Waiting for containers to be ready..."
          sleep 10

      - name: Clean up old images
        run: docker image prune -f 